controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 27.10.2019
 * Time: 19:14
 */

namespace app\controllers;
use app\models\Cart;
use Yii;
use app\models\Order;
use app\models\OrderItems;


use yii\web\Controller;
use yii\web\Request;

class CartController extends Controller {

    public function actionAdd(){
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        $product = Cart::findOne($id);
        if(empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionClear(){
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionView(){
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if( $order->load(Yii::$app->request->post())){
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            if($order->save()){
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят');
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error', 'Ошибка!');
            }
        }

        return $this->render('view', compact('session', 'order'));
    }

    public function actionDel(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        return $this->render('table', compact('session'));
    }

    protected function saveOrderItems($items, $order_id){
        foreach ($items as $id => $item){
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['product_title'];
            $order_items->price = $item['product_price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty']*$item['product_price'];
            $order_items->save();
        }
    }
}

controllers/CatalogController.php
<?php


namespace app\controllers;

use app\models\Catalog;
use yii\web\Controller;
use yii\helpers\Html;
use Yii;
use yii\db\Query;

class CatalogController extends Controller {


    public function actionIndex() {
        $search = new Catalog();
        if($search->load(Yii::$app->request->post())) {
            if ($search->validate()){
                $search_word = Html::encode($search->search_word);
                $category = Html::encode($search->category);
                if($category == '0'){
                    $category = '';
                }
                $color = $this->setSearchValue(Html::encode($search->color));
                $type = $this->setSearchValue(Html::encode($search->type));
                $status = $this->setSearchValue(Html::encode($search->status));
                $price = $this->setSearchValue(Html::encode($search->price));

                $catalog = (new Query())
                    ->select('*')
                    ->from('products')
                    ->where(['and', ['like','product_title', $search_word], ['like','product_category_id', $category], ['like','product_color', $color], ['like','product_type', $type], ['like','product_status', $status]])
                    ->all();
                $catalog = $this->repackCatalog($catalog);
            }
        }else {
            $catalog = (new Query())
                ->select('*')
                ->from('products')
                ->all();
            $catalog = $this->repackCatalog($catalog);
        }


        return $this->render('index', compact('catalog', 'search', 'search_word', 'category', 'color', 'type', 'status',  'price' ));
    }

    public function setSearchValue($col){
        switch ($col){
            case '1':
                $col = '0';
                break;
            case '2':
                $col = '1';
                break;
            case '3':
                $col = '2';
                break;
            case '4':
                $col = '3';
                break;
            default:
                $col = '';

        }
        return $col;
    }
    public function repackCatalog($arr){
        $repack = [];
        foreach ($arr as $key =>$item){
            switch ($item['product_category_id']) {
                case '1':
                    $item['product_category_id'] = 'Футболки';
                    break;
                case '2':
                    $item['product_category_id'] = 'Джинсы';
                    break;
                case '3':
                    $item['product_category_id'] = 'Рубашки';
                    break;
                case '4':
                    $item['product_category_id'] = 'Толстовки';
                    break;
            }
            switch ($item['product_status']) {
                case'0':
                    $item['product_status'] = 'В наличии';
                    break;
                case'1':
                    $item['product_status'] = 'Временно отсутствует';
                    break;
                case'2':
                    $item['product_status'] = 'Доступен для заказа';
                    break;
                case'3':
                    $item['product_status'] = 'Не доступен для заказа';
                    break;
            }
            if ($item['product_type'] == '0') {
                $item['product_type'] = 'Мужкая';
            }
            if ($item['product_type'] == '1') {
                $item['product_type'] = 'Женская';
            }
            switch ($item['product_color']) {
                case'0':
                    $item['product_color'] = 'Темные';
                    break;
                case'1':
                    $item['product_color'] = 'Светлые';
                    break;
                case'2':
                    $item['product_color'] = 'С принтом';
                    break;
            }
            $repack[] = $item;
        }
        return $repack;
    }

}

views/layouts/_main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;

//$js = <<<JS
//    $('.add_card').on('click', function(){
//        $.ajax({
//        url: '/cart/add',
//        data: {test: '123'},
//        type: 'POST',
//        success: function(res){
//            console.log(res);
//        },
//        error: function(){
//            console.log('Error!');
//        }
//        });
//    });
//
//JS;
//$this->registerJs($js);

$domain = Url::base(true);

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Catalog', 'url' => ['/catalog/index']],
            ['label' => 'Your cart', 'url' => ['#'], 'linkOptions' => ['class' => 'tempCart']],
            Yii::$app->user->isGuest ? (
            ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            ),
            ['label' => 'Shopping Card', 'url' => ['/cart/view']],

        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php
\yii\bootstrap\Modal::begin([
    'header' => '<h2>Корзина</h2>',
    'id' => 'cart',
    'size' => 'modal-lg',
    'footer' => '<button type="button" class="btn btn-success" data-dismiss="modal">Продолжить</button>
                <a href="' . \yii\helpers\Url::to(['cart/view']) . '" class="btn btn-primary">Оформить</a>
                <button type="button" class="btn btn-danger clear-cart">Очистить корзину</button>'
]);
\yii\bootstrap\Modal::end();

?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>
