models/Cart.php
<?php

namespace app\models;
use yii\db\ActiveRecord;


class Cart extends ActiveRecord {

    public static function tableName()
    {
        return 'products';
    }


    public function addToCart($product, $qty = 1){
        if(isset($_SESSION['cart'][$product->product_id])){
            $_SESSION['cart'][$product->product_id]['qty'] +=$qty;
        }else {
            $_SESSION['cart'][$product->product_id] = [
                'qty' => $qty,
                'product_title' => $product->product_title,
                'product_price' => $product->product_price,
                'product_img' => $product->product_img
            ];
        }
        $_SESSION['cart.qty'] = isset($_SESSION['cart.qty']) ? $_SESSION['cart.qty']+$qty : $qty;
        $_SESSION['cart.sum'] = isset($_SESSION['cart.sum']) ? $_SESSION['cart.sum']+$qty*$product->product_price : $qty*$product->product_price;

    }

    public function recalc($id){
        if(!isset($_SESSION['cart'][$id])) return false;

        $qtyMinus = $_SESSION['cart'][$id]['qty'];
        $sumMinus = $_SESSION['cart'][$id]['qty']*$_SESSION['cart'][$id]['product_price'];
        $_SESSION['cart.qty'] -= $qtyMinus;
        $_SESSION['cart.sum'] -= $sumMinus;
        unset($_SESSION['cart'][$id]);
    }
}

controllers/CardController.php
<?php


namespace app\controllers;

use yii\web\Controller;
use yii\db\Query;


class CardController extends Controller {

    public function actionIndex($id = null) {

        if(!$id){
            $query = null;
        }else{
            $query = (new Query())
                ->select('*')
                ->from('products')
                ->where(['product_id' => $id])
                ->one();

        }

        return $this->render('index', compact('id', 'query'));
    }
}

controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: Pavel
 * Date: 27.10.2019
 * Time: 19:14
 */

namespace app\controllers;
use app\models\Cart;
use Yii;
use app\models\Order;
use app\models\OrderItems;


use yii\web\Controller;
use yii\web\Request;

class CartController extends Controller {

    public function actionAdd(){
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $qty = !$qty ? 1 : $qty;
        $product = Cart::findOne($id);
        if(empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $qty);
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionClear(){
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionView(){
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if( $order->load(Yii::$app->request->post())){
            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            if($order->save()){
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят');
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error', 'Ошибка!');
            }
        }

        return $this->render('view', compact('session', 'order'));
    }

    public function actionDel(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        return $this->render('table', compact('session'));
    }

    protected function saveOrderItems($items, $order_id){
        foreach ($items as $id => $item){
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['product_title'];
            $order_items->price = $item['product_price'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty']*$item['product_price'];
            $order_items->save();
        }
    }
}

views/cart/cart-modal.php
<?php
use \yii\helpers\Html;
use yii\helpers\Url;
$domain = Url::base(true);
?>
<?php if(!empty($session['cart'])): ?>
    <div class="table-responsive">
        <table class="table table-hover table-stripped">
            <thead>
            <tr>
                <th>Фото</th>
                <th>Наименование</th>
                <th>Кол-во</th>
                <th>Цена</th>
                <th><span class="glyphicon gliphicon-remove" aria-hidden="true"></span></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($session['cart'] as $id => $item): ?>
                <tr>
                    <td><?=Html::img($domain.'/web/img/'.$item['product_img']) ?></td>
                    <td><?=$item['product_title'] ?></td>
                    <td><?=$item['qty'] ?></td>
                    <td><?=$item['product_price'] ?></td>
                    <td><span class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true" data-id="<?=$id; ?>"></span></td>
                </tr>
            <?php endforeach; ?>
                <tr>
                    <td colspan="4">Итого: </td>
                    <td><?= $session['cart.qty'] ?></td>
                </tr>
                <tr>
                    <td colspan="4">Сумма: </td>
                    <td><?= $session['cart.sum'] ?></td>
                </tr>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <h3>Корзина пуста</h3>
<?php endif;?>

views/cart/table.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
$domain = Url::base(true);
?>

<?php if(!empty($session['cart'])): ?>
    <div class="table-responsive">
        <table class="table table-hover table-stripped">
            <thead>
            <tr>
                <th>Фото</th>
                <th>Наименование</th>
                <th>Кол-во</th>
                <th>Цена</th>
                <th>Сумма</th>
                <th><span class="glyphicon gliphicon-remove" aria-hidden="true"></span></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($session['cart'] as $id => $item): ?>
                <tr>
                    <td><?=Html::img($domain.'/web/img/'.$item['product_img']) ?></td>
                    <td><a href="<?= Url::to(['card/index', 'id' => $id]); ?>"><?=$item['product_title'] ?></a></td>
                    <td><?=$item['qty'] ?></td>
                    <td><?=$item['product_price'] ?></td>
                    <td><?=$item['product_price']*$item['qty'] ?></td>
                    <td><span class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true" data-id="<?=$id; ?>"></span></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="4">Итого: </td>
                <td><?= $session['cart.qty'] ?></td>
                <td></td>
            </tr>
            <tr>
                <td colspan="4">Сумма: </td>
                <td><?= $session['cart.sum'] ?></td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <h3>Корзина пуста</h3>
<?php endif;?>

views/cart/view.php
<div class="container">
    <?php
    use yii\helpers\Url;
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    $domain = Url::base(true);
    ?>
    <div id="inside">
        <?php if(!empty($session['cart'])): ?>
        <div class="table-responsive">
            <table class="table table-hover table-stripped">
                <thead>
                <tr>
                    <th>Фото</th>
                    <th>Наименование</th>
                    <th>Кол-во</th>
                    <th>Цена</th>
                    <th>Сумма</th>
                    <th><span class="glyphicon gliphicon-remove" aria-hidden="true"></span></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($session['cart'] as $id => $item): ?>
                    <tr>
                        <td><?=Html::img($domain.'/web/img/'.$item['product_img']) ?></td>
                        <td><a href="<?= Url::to(['card/index', 'id' => $id]); ?>"><?=$item['product_title'] ?></a></td>
                        <td><?=$item['qty'] ?></td>
                        <td><?=$item['product_price'] ?></td>
                        <td><?=$item['product_price']*$item['qty'] ?></td>
                        <td><span class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true" data-id="<?=$id; ?>"></span></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="4">Итого: </td>
                    <td><?= $session['cart.qty'] ?></td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="4">Сумма: </td>
                    <td><?= $session['cart.sum'] ?></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
        <?php else: ?>
            <h3>Корзина пуста</h3>
        <?php endif;?>
    </div>

        <?php $form = ActiveForm::begin()?>
        <?= $form->field($order, 'name')?>
        <?= $form->field($order, 'email')?>
        <?= $form->field($order, 'phone')?>
        <?= $form->field($order, 'address')?>
        <?= Html::submitButton('Заказать', ['class' => 'btn btn-success']) ?>
        <?php ActiveForm::end() ?>

</div>
